# Settings for libraries used by specific LAMMPS packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =   -I../../lib/meam 
PKG_PATH =  -L../../lib/meam 
PKG_LIB =   -lmeam 
PKG_CPP_DEPENDS = 
PKG_LINK_DEPENDS = 

PKG_SYSINC =  $(meam_SYSINC) 
PKG_SYSLIB =  $(meam_SYSLIB) 
PKG_SYSPATH = $(meam_SYSPATH) 
